# Generated by Django 3.1.1 on 2020-09-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('mail', models.CharField(max_length=100, verbose_name='Почта')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема')),
                ('comment', models.TextField(verbose_name='Коммент')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='newprice',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
