# Generated by Django 3.1.1 on 2020-10-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200930_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_disc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Цена со скидкой'),
        ),
    ]
