# Generated by Django 3.1.2 on 2020-10-02 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_price_disc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applications',
            options={'verbose_name': 'Заявка cо страницы контактов', 'verbose_name_plural': 'Заявка со страницы контактов'},
        ),
    ]
